---
title: "Occurrance of Dementia"
author: "Y3865992"
date: "02/12/2020"
output: html_document
bibliography: [References/references.bib]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)
```

```{r packages}
library(tidyverse)
library(caret)
library(GGally)
library(readxl)
library(dplyr)
```

```{r functions}
# word_count calculates the word count for files both rmd and md
source("Word_count/word_count_addin.R")
```

```{r import, include=FALSE}

# import the data from separate sheets as different data sets
visit_data <- read_xlsx("Data/raw_data/dementia.xlsx",
                         sheet = "visit data")

patient_data <- read_xlsx("Data/raw_data/dementia.xlsx",
                          sheet = "patient data")

# tidy the data so that column names are lowercase and spaces are filled with underscores using the janitor function
visit_data <- visit_data %>%
  janitor::clean_names()

patient_data <- patient_data %>%
  janitor::clean_names()

```

```{r merge, include=FALSE}
# merge the two data sets into one so analysis can be carried out

dementia_data <- merge(visit_data, patient_data, by = "subject_id")

# After merging for some patients their second MRI was listed above their first, to change this I arranged the data by first subject id then MRI number in ascending order
dementia_data <- dementia_data %>%
  arrange(subject_id, mri_number)
```

```{r filter, include=FALSE}

# take the rows out of the dataset with missing data
dementia_data <- dementia_data %>%
filter(!is.na(ses))

```

```{r summary, include=FALSE}
# summarise the merged data set
dementia_sum <- summary(dementia_data)
dementia_sum
```

# Introduction
R is the best

# Methods

# Results

```{r figures}

```
# Discussion

## Word Count

```{r word count, include=FALSE}
# using a word count addin to calculate the word count of the rmd file and the read.me file

# use separate word counts for the rmd and the readme file 
# can add them together to show total word count
wc_rmd <- count_words("Dementia_Occurrence.Rmd")
wc_readme <- count_words("README.md")

```
This document: `r wc_rmd`

The README file: `r wc_readme`

Total:  `r wc_rmd + wc_readme`

# Bibliography

