---
title: "Occurrance of Dementia"
author: "Y3865992"
date: "02/12/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)
```

```{r packages}
library(tidyverse)
library(caret)
library(GGally)
library(readxl)
```

```{r import}
# import the data from separate sheets as different data sets
visit_data <- read_xlsx("raw_data/dementia.xlsx",
                         sheet = "visit data")

patient_data <- read_xlsx("raw_data/dementia.xlsx",
                          sheet = "patient data")
```

```{r tidy}
# tidy the data so that column names are lowercase and spaces are filled with underscores
visit_data <- visit_data %>%
  janitor::clean_names()

patient_data <- patient_data %>%
  janitor::clean_names()

```

```{r summarise}
# summarise both sets of data
visit_sum <- summary(visit_data)

patient_sum <- summary(patient_data)

```

# Introduction

# Methods

# Results

```{r figures}

```
# Discussion

# References